class_name ResourceCatalog extends RefCounted

const SWORD_CARD_PATHS: Array[String] = [
	"res://data/cards/sword/bu_fa.tres",
	"res://data/cards/sword/bu_mie_jian_xin.tres",
	"res://data/cards/sword/cang_feng_shou.tres",
	"res://data/cards/sword/ce_shen.tres",
	"res://data/cards/sword/chi_xiao.tres",
	"res://data/cards/sword/chong_neng_zhan.tres",
	"res://data/cards/sword/ci_jian.tres",
	"res://data/cards/sword/ding_shi.tres",
	"res://data/cards/sword/duan_pai.tres",
	"res://data/cards/sword/duan_yue_zhan.tres",
	"res://data/cards/sword/fan_shou.tres",
	"res://data/cards/sword/fan_zhen.tres",
	"res://data/cards/sword/fen_tian.tres",
	"res://data/cards/sword/feng_chi.tres",
	"res://data/cards/sword/feng_juan_can_yun.tres",
	"res://data/cards/sword/feng_lei_yin.tres",
	"res://data/cards/sword/feng_xue.tres",
	"res://data/cards/sword/hui_feng.tres",
	"res://data/cards/sword/hui_qi.tres",
	"res://data/cards/sword/hui_xiang_jian.tres",
	"res://data/cards/sword/huo_xing.tres",
	"res://data/cards/sword/huo_yu.tres",
	"res://data/cards/sword/jian_bu.tres",
	"res://data/cards/sword/jian_dan.tres",
	"res://data/cards/sword/jian_ge.tres",
	"res://data/cards/sword/jian_jue.tres",
	"res://data/cards/sword/jian_ming.tres",
	"res://data/cards/sword/jian_qi.tres",
	"res://data/cards/sword/jian_qi_mu.tres",
	"res://data/cards/sword/jian_ying.tres",
	"res://data/cards/sword/jian_yu.tres",
	"res://data/cards/sword/jian_yu_tong_xin.tres",
	"res://data/cards/sword/ju_qi.tres",
	"res://data/cards/sword/kai_tian_zhan.tres",
	"res://data/cards/sword/kong_gu_hui_xiang.tres",
	"res://data/cards/sword/kong_ming_jian.tres",
	"res://data/cards/sword/kuai_jian.tres",
	"res://data/cards/sword/lan_jian.tres",
	"res://data/cards/sword/lian_ci.tres",
	"res://data/cards/sword/lian_huan_jian.tres",
	"res://data/cards/sword/lie_kou.tres",
	"res://data/cards/sword/lie_shan_pi.tres",
	"res://data/cards/sword/liu_huo.tres",
	"res://data/cards/sword/liu_yun_jian.tres",
	"res://data/cards/sword/na_qi.tres",
	"res://data/cards/sword/ning_qi.tres",
	"res://data/cards/sword/po_jia.tres",
	"res://data/cards/sword/po_kong_zhan.tres",
	"res://data/cards/sword/po_zhen.tres",
	"res://data/cards/sword/qi_hai.tres",
	"res://data/cards/sword/qi_zhuan.tres",
	"res://data/cards/sword/qian_yin.tres",
	"res://data/cards/sword/qian_zhan.tres",
	"res://data/cards/sword/qiang_pi.tres",
	"res://data/cards/sword/qiang_pi_plus.tres",
	"res://data/cards/sword/qie_mai.tres",
	"res://data/cards/sword/qing_feng_zhan.tres",
	"res://data/cards/sword/qing_mang.tres",
	"res://data/cards/sword/ran_jian.tres",
	"res://data/cards/sword/ru_yan.tres",
	"res://data/cards/sword/san_luo_jian.tres",
	"res://data/cards/sword/shan_ji.tres",
	"res://data/cards/sword/shi_ling.tres",
	"res://data/cards/sword/shi_xu_ling.tres",
	"res://data/cards/sword/shou_shi.tres",
	"res://data/cards/sword/shou_zhong_dai_gong.tres",
	"res://data/cards/sword/shuang_xiang.tres",
	"res://data/cards/sword/shun_pu.tres",
	"res://data/cards/sword/sui_xing_jian.tres",
	"res://data/cards/sword/tai_xu_ju_qi.tres",
	"res://data/cards/sword/tai_yi_lun.tres",
	"res://data/cards/sword/tian_he_yi_jian.tres",
	"res://data/cards/sword/tian_luo.tres",
	"res://data/cards/sword/wan_jian_gui_zong.tres",
	"res://data/cards/sword/wu_bu_yi_sha.tres",
	"res://data/cards/sword/wu_ying_jian.tres",
	"res://data/cards/sword/xiao_zhou_tian.tres",
	"res://data/cards/sword/xu_kong_jian.tres",
	"res://data/cards/sword/xu_shi.tres",
	"res://data/cards/sword/xuan_jia.tres",
	"res://data/cards/sword/xuan_wu_fan.tres",
	"res://data/cards/sword/yan_jian.tres",
	"res://data/cards/sword/yan_xi.tres",
	"res://data/cards/sword/yang_jian_shi.tres",
	"res://data/cards/sword/ye_huo_lun.tres",
	"res://data/cards/sword/yi_pai.tres",
	"res://data/cards/sword/yi_qi.tres",
	"res://data/cards/sword/yin_qi_zhan.tres",
	"res://data/cards/sword/yin_ran.tres",
	"res://data/cards/sword/yu_bu.tres",
	"res://data/cards/sword/yu_jian_dun.tres",
	"res://data/cards/sword/yu_jian_fan_ji.tres",
	"res://data/cards/sword/yu_yin.tres",
	"res://data/cards/sword/yun_ti.tres",
	"res://data/cards/sword/zhan.tres",
	"res://data/cards/sword/zhan_nian.tres",
	"res://data/cards/sword/zhan_plus.tres",
	"res://data/cards/sword/zhen_jiao.tres",
	"res://data/cards/sword/zhen_mai.tres",
	"res://data/cards/sword/zhuan_shou.tres",
	"res://data/cards/sword/zhui_jian.tres",
]

const GEM_PATHS: Array[String] = [
	"res://data/gems/amber.tres",
	"res://data/gems/jade.tres",
	"res://data/gems/ruby.tres",
	"res://data/gems/sapphire.tres",
]

const RELIC_PATHS: Array[String] = [
	"res://data/relics/ancient_coin.tres",
	"res://data/relics/black_iron_scabbard.tres",
	"res://data/relics/bronze_bell.tres",
	"res://data/relics/cloth_bracer.tres",
	"res://data/relics/cracked_jade_charm.tres",
	"res://data/relics/ember_talisman.tres",
	"res://data/relics/empty_seat_lantern.tres",
	"res://data/relics/exquisite_pagoda.tres",
	"res://data/relics/flawless_golden_body.tres",
	"res://data/relics/heart_guard_mirror.tres",
	"res://data/relics/heavenly_river_case.tres",
	"res://data/relics/jade_chain_ring.tres",
	"res://data/relics/loose_page.tres",
	"res://data/relics/mind_cutting_lamp.tres",
	"res://data/relics/myriad_array_plate.tres",
	"res://data/relics/needle_compass.tres",
	"res://data/relics/nine_turn_furnace.tres",
	"res://data/relics/old_banner.tres",
	"res://data/relics/qi_gourd.tres",
	"res://data/relics/short_incense.tres",
	"res://data/relics/small_elixir.tres",
	"res://data/relics/star_sand_inkstone.tres",
	"res://data/relics/sword_tassel.tres",
	"res://data/relics/taixu_sword_seal.tres",
	"res://data/relics/thunder_trial_wood.tres",
	"res://data/relics/warding_umbrella.tres",
	"res://data/relics/whetstone.tres",
	"res://data/relics/wind_return_jade.tres",
	"res://data/relics/wooden_sword_case.tres",
	"res://data/relics/yin_yang_fish_talisman.tres",
]

const CHARACTER_CARD_PATHS: Dictionary = {
	&"sword": SWORD_CARD_PATHS,
}

static func card_paths(character_id: StringName) -> Array[String]:
	var paths: Array[String] = []
	paths.assign(CHARACTER_CARD_PATHS.get(character_id, []))
	return paths

static func gem_paths() -> Array[String]:
	return GEM_PATHS.duplicate()

static func relic_paths() -> Array[String]:
	return RELIC_PATHS.duplicate()
